
FROM ubuntu:14.04
MAINTAINER Ghislain Guiot <gt.ghislain@gmail.com>

ADD bearded-basket bearded-basket
 
EXPOSE 8000
 
ENTRYPOINT ["/bearded-basket"]
# ENTRYPOINT ["/bearded-basket", "-db", "root:@192.168.0.65:3306/prod"]
